CXX = i686-w64-mingw32-g++
OBJECTS = src/reactor.o src/resource.o src/image_resource.o src/text_resource.o src/color_resource.o src/music_manager.o src/aabb.o src/module.o src/context.o src/world.o src/entity.o src/projectile.o src/entity_manager.o src/gui_element.o src/gui_manager.o src/sound.o
CXXFLAGS = -DGLEW_STATIC -Iinclude -std=c++11 -g -gstabs -ggdb -Wall -Werror -I/usr/i686-w64-mingw32/include -I/usr/local/include

all: src/main.o $(OBJECTS)
	$(CXX) src/main.o $(OBJECTS) -std=c++11 -static -static-libgcc -static-libstdc++ -L/usr/i686-w64-mingw32 -lmingw32 -lSDL2main -lSDL2_image -lSDL2_mixer -lSDL2 -mwindows -lm -ldinput8 -ldxguid -ldxerr8 -luser32 -lgdi32 -lwinmm -limm32 -lole32 -loleaut32 -lshell32 -lversion -luuid -lm -lBox2D -lglew32 -lopengl32 -lglu32 -o squeezebox.exe
clean:
	rm src/*.o
